Performance improvements
darrenks/golfscript pull request #1
Opened 2022-06-10 18:28 UTC by lynn

As mentioned in my email, this makes `array string *` and `array.to_gs` not quadratic.

I tested the resulting change on 1906 GolfScript solutions that Sisyphus in the code.golf Discord had scraped from http://golf.shinh.org. I wondered if I could make this test suite run a little faster so I used ruby-prof to benchmark the execution…

It turns out that a lot of time is spent on `Gint.new` and `Gint.val`. So I had the idea to get rid of `Gint` and instead work with plain `Numeric` everywhere. This works and makes all programs about 25% faster, but this PR much more complicated 🙂 

Feeling confident about having an exhaustive test suite I made some other performance improvements here and there.

BTW, to my surprise, the interpreter is supported just fine by Ruby 3 even though it was written for 1.9! I only have to run `ruby --encoding ASCII-8BIT golfscript.rb` so that it doesn't complain about non-UTF-8 strings.

2022-06-10 18:36 UTC, lynn commented on golfscript.rb
>  	$stack.pop
`gpop` is called super often, so I tried rewriting it a couple of ways to squeeze more performance out (honestly mostly for fun at this point). It seems this is a bit faster than a block.

2022-06-10 18:36 UTC, lynn commented on golfscript.rb
> +	def gscoerce(b)
I had to rename `coerce` to `gscoerce` because there is already a method named `coerce` on Ruby's `Numeric` and it was messing things up.

2022-06-10 18:36 UTC, lynn commented on golfscript.rb
> +			@val[1..-1].each{|i|r=r.concat(b); r=r.concat(i)}
This is the quadraticity fix for `*`

2022-06-10 18:36 UTC, lynn commented on golfscript.rb
> +		Gstring.new(r)
This is the quadraticity fix for `Garray#to_gs`

2022-06-10 20:30 UTC, darrenks commented on golfscript.rb
> +			when String then a.bytes
Hey, I believe this was not in ruby 1.8. It may be turn out to be unreasonable to try to have code compatible with 1.8 - 3.0+ but I'd like to try if possible.

2022-06-10 20:36 UTC, darrenks requested changes
Hey Lynn thanks for the major quadratic improvements and general speed improvements. Would it be possible for you to send me the code you used to test it on the ~1000 programs? That would be very useful for me in reviewing future changes and I really appreciate the thoroughness.

Only issue I see far is the note about 1.8.

Also I will be traveling for ~1.5 weeks and might not be able to fully review until back from that, so please be patient.

2022-06-10 22:46 UTC, lynn commented
I added the test suite code. When you first run `python3 test_suite.py` it tells you what file to download and where to extract it 👍 

![image](https://user-images.githubusercontent.com/16232127/173159650-dbb7c5db-4a40-4998-a8e5-56e8c69ba6cd.png)

2022-06-18 21:12 UTC, darrenks commented on test_suite.py
>          if prob.name in ["area of triangle", "0_5 broken keyboard", "Cancel fractions", "Equal Temperament", "MIDI note number to frequency", "Numloop"]: continue
"Concentric Circles" too

2022-06-19 20:25 UTC, darrenks commented
I've read through all the changes and tried to understand them. I believe I'm ok with everything except the change from Gint to using Numeric. It complicates the code and makes it harder to reason about (not that the existing Golfscript code is good in that regard). I would guess that you have covered all your tracks and that it wouldn't cause any bugs... But I'm not 100% sure, since these tests are only features that have been useful in actual codegolf problems rather than all edge cases possible. And Golfscript lacks any unit tests. I considered trying to write Golfscript like that originally (for the other types too) but got too confused :)

I'm definitely for asymptotic performance improvements or even simple constant improvements (of which you made several), but I think if we really wanted the language to be fast we'd need to start over from scratch and build a JIT or an interpreter in a fast language, but this would be difficult due to the extreme dynamic nature of the language (I'm referring to rarely used features like overwriting builtins dynamically).

Also I'm a bit of a noob when it comes to managing pull requests in github so bear with me if you change this initial commit that the others are stacked on. We will get the other changes in though!

Thanks for your help making gs faster.

2022-06-19 20:29 UTC, darrenks commented on test_suite.py
> +        if prob.name.lower() in ["helloworld", "christmas tree", "multiplication table"]: continue
Also on my system (which is case insensitive), "Tic Tac Toe" is broken due to this issue

2022-09-05 14:28 UTC, closed without merging